{% set name = "pyiron_gpl" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron-gpl-{{ version }}.tar.gz
  sha256: 03139fb84de14a95ec34433d7403120d58033dd1285784d97379a40551f9f74e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - molmod >=1.4.8
    - numpy >=1.20.1
    - pyiron_atomistics >=0.2.8
    - python >=3.5
    - spglib >=1.16.1
    - scipy >=1.6.1
    - quickff >=2.2.4
    - tamkin >=1.2.6
    - yaff >=1.4.2

test:
  imports:
    - pyiron_gpl
    - pyiron_gpl.elastic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_gpl
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Additional modules for the pyiron IDE licensed under GPLv3'
  description: |
    Additional modules for the pyiron IDE licensed under GPLv3
  doc_url: https://github.com/pyiron/pyiron_gpl
  dev_url: https://github.com/pyiron/pyiron_gpl

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
